version: "3.9"

services:
  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py createsuperuser --noinput || true && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    env_file:
      - deploy.env
  mysql:
    image: mysql
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - deploy.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  db-volume:
