# Generated by Django 4.0.3 on 2022-04-01 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('layout', models.CharField(choices=[('1x1', '1x1'), ('1x2', '1x2'), ('1x3', '1x3'), ('2x1', '2x1'), ('2x2', '2x2'), ('2x3', '2x3'), ('3x1', '3x1'), ('3x2', '3x2'), ('3x3', '3x3')], default='1x1', max_length=10)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.place')),
            ],
        ),
    ]
