# Generated by Django 4.0.3 on 2022-04-01 12:21

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=mapbox_location_field.models.LocationField(
                default='', map_attrs={}),
            preserve_default=False,
        ),
    ]
