# Generated by Django 3.2.12 on 2022-04-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_image_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
