# Generated by Django 4.0.3 on 2022-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_place_latitude_remove_place_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default='', upload_to='travellog'),
            preserve_default=False,
        ),
    ]
