# Generated by Django 4.0.3 on 2022-04-02 03:26

from django.db import migrations, models
import map.storage


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_image_url_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='', storage=map.storage.SmmsStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
